// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT___WAP.Entities;

#nullable disable

namespace PROJECT___WAP.Migrations
{
    [DbContext(typeof(RouteContext))]
    partial class RouteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("PROJECT___WAP.Entities.Route", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostPerKM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Length")
                        .HasColumnType("REAL");

                    b.Property<float>("Payment")
                        .HasColumnType("REAL");

                    b.Property<string>("StartingPoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalWeight")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
